# main.yml

# Workflow's name
name: Build Electron Paste For Win/Linux
# Workflow's trigger
on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      # Push events on main branch
      - windows-pack

# Workflow's jobs
jobs:
  # job's id
  release:
    # job's name
    name: build and release electron paste

    # the type of machine to run the job on
    runs-on: ${{ matrix.os }}

    # create a build matrix for jobs
    strategy:
      matrix:
        os: [ windows-2016 ]

    # create steps
    steps:
      # step1: check out repository
      - name: Check out git repository
        uses: actions/checkout@master

      # step2: install node env
      - name: Install Node.js
        uses: actions/setup-node@master
        with:
          node-version: 14

      # step3: npm install build tools
      - name: npm install windows build tools
        if: matrix.os == 'windows-2016'
        run: |
          npm install --global --production windows-build-tools@4.0.0 && npm install node-gyp@latest && npm config set python python2.7 && npm config set msvs_version 2017

      # step4: npm install
      - name: npm install
        run: |
          npm install

      # step5: build app for mac/win
      - name: build windows app
        if: matrix.os == 'windows-2016'
        run: |
          npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # step7: upload artifacts
      - name: upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ${{ matrix.os }}
          path: build
